stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/

test:
  stage: test
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
    reports:
      junit: target/surefire-reports/*.xml

deploy:
  stage: deploy
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - echo "Deploying application..."
  only:
    - main
